Repository chaesc1/WAAWAAWAA, pull requests merged in 2023-10, with the labels that each got.

#45 말풍선design ,메세지 하나씩 띄우는거 처리 X
  App.js
  src/screens/QuizPage_test.js
  src/screens/StoryPage.js
  yarn.lock
Labels: 🌻정훈🌻, 🎨디자인🎨

#50 LandingPage -> OnboardingPage
  App.js
  assets/animations/SadAni.json
  package-lock.json
  package.json
  src/screens/LandingPage.js
  src/screens/OnboardingPage.js
  yarn.lock
Labels: 🌻정훈🌻, 🖥️기능🖥️, 🎨디자인🎨

#51 MyPage header backbutton 수정
  App.js
  src/screens/MyPage.js
Labels: 🌻정훈🌻, 🎨디자인🎨

#52 [FEATURE] 마이페이지, footer 전체 수정
  App.js
  assets/animations/logout.json
  assets/animations/mypage.json
  assets/images/gold.png
  ios/Podfile.lock
  src/components/footer.js
  src/screens/MyPage.js
  src/screens/StaticsPage.js
Labels: 🌼예림🌼

#56 통계페이지 반응형 작업 / 뒤로가기 푸터 깨짐 수정
  src/screens/StaticsPage.js
Labels: 🌻정훈🌻, 🎨디자인🎨

#57 Design/위험의심 내용 수정
  src/screens/StaticsPage.js
Labels: 🌻정훈🌻, 🎨디자인🎨

#58 Design/통계페이지footer제거
  src/screens/StaticsPage.js
Labels: 🌻정훈🌻, 🎨디자인🎨

#60 refactor : 필요없는 파일제거, 파일명 변경
  App.js
  src/screens/CounsellingBackUp.js
  src/screens/CounsellingPage.js
  src/screens/CounsellingRe.js
  src/screens/LandingPage.js
  src/screens/LandingPageBackup.js
  src/screens/LoginPage.js
  src/screens/Quiz.js
  src/screens/QuizMainPage.js
  src/screens/QuizPage.js
  src/screens/QuizPage_BackUp.js
  src/screens/QuizPage_test copy.js
  src/screens/QuizPage_test.js
  src/screens/RegisterPage.js
  src/screens/STTS.js
  src/screens/newLoginPage.js
  src/screens/newRegister.js
Labels: 🌻정훈🌻
