Repository chaesc1/WAAWAAWAA, pull requests merged in 2023-09, with the labels that each got.

#24 #19. 통계 페이지 생성 후, 기능 추가
  App.js
  src/screens/MyPage.js
  src/screens/StaticsPage.js
  yarn.lock
Labels: 🌼예림🌼, 🖥️기능🖥️

#26 Text 수정
  App.js
  src/screens/MyPage.js
  src/screens/RegisterPage.js
Labels: 🌻정훈🌻, 🎨디자인🎨

#27 Cjh
  App.js
  assets/images/login.png
  assets/images/signup.png
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/footer.js
  src/screens/LandingPage.js
  src/screens/LoginPage.js
  src/screens/newLoginPage.js
  src/screens/newRegister.js
  theme/index.js
  yarn.lock
Labels: 🌻정훈🌻, 🖥️기능🖥️, 🎨디자인🎨

#31 Yerim
  ios/Podfile.lock
  package-lock.json
  src/screens/StaticsPage.js
  src/utils/isTokenAvailable.js
Labels: 🌼예림🌼, 🖥️기능🖥️, 🎨디자인🎨

#34 유효성 검사 기능구현
  package-lock.json
  package.json
  src/screens/MemberMainPage.js
  src/screens/newLoginPage.js
  src/screens/newRegister.js
  yarn.lock
Labels: bug, 🌻정훈🌻, 🎨디자인🎨

#35 애니메이션 추가
  assets/animations/loading.json
  assets/animations/newBear.json
  src/api/OpenAI.js
  src/components/QuizFeature.js
  src/components/feature.js
  src/screens/CounsellingRe.js
  src/screens/Quiz.js
  src/screens/newLoginPage.js
  src/screens/newRegister.js
Labels: 🌻정훈🌻, 🎨디자인🎨

#36 메인메뉴 UI 전체 변경
  assets/animations/BlueBear.json
  assets/animations/GreenBear.json
  assets/animations/YellowBear.json
  assets/images/background.png
  assets/images/line.png
  package-lock.json
  package.json
  src/components/MenuCard.js
  src/constants/index.js
  src/screens/MemberMainPage.js
  yarn.lock
Labels: 🌻정훈🌻, 🎨디자인🎨
